from cook import Importer
import os

def ETL():
    RECIPE_ENGINE = os.environ.get('FACDB_ENGINE', '')
    BUILD_ENGINE=os.environ.get('BUILD_ENGINE', '')

    #load geoboundaries
    importer = Importer(RECIPE_ENGINE, BUILD_ENGINE)
    importer.import_table(schema_name='dcp_boroboundaries_wi')
    importer.import_table(schema_name='dcp_censustracts')
    importer.import_table(schema_name='dcp_councildistricts')
    importer.import_table(schema_name='dcp_cdboundaries')
    importer.import_table(schema_name='dcp_ntaboundaries')
    importer.import_table(schema_name='dcp_policeprecincts')
    importer.import_table(schema_name='doitt_zipcodeboundaries')
    importer.import_table(schema_name='doitt_buildingcentroids')
    importer.import_table(schema_name='dcp_school_districts')

    #load reference table
    importer.import_table(schema_name='dcp_facilities')
    importer.import_table(schema_name='facilities_classification')
    importer.import_table(schema_name='dcp_mappluto')
    importer.import_table(schema_name='zipcode_city_lookup')

    # load facilities
    importer.import_table(schema_name='dcp_pops')
    importer.import_table(schema_name='dpr_parksproperties')
    importer.import_table(schema_name='fdny_firehouses')
    importer.import_table(schema_name='moeo_socialservicesiteloactions')
    importer.import_table(schema_name='nysdec_lands')
    importer.import_table(schema_name='nysparks_historicplaces')
    importer.import_table(schema_name='nysparks_parks')
    importer.import_table(schema_name='usdot_ports')
    importer.import_table(schema_name='usnps_parks')

    # future refactoring
    # importer.import_table(schema_name='acs_daycareheadstart')
    # importer.import_table(schema_name='bpl_libraries')
    # importer.import_table(schema_name='dca_operatingbusinesses')
    # importer.import_table(schema_name='dcas_colp')
    # importer.import_table(schema_name='dcla_culturalinstitutions')
    # importer.import_table(schema_name='dcp_pops')
    # importer.import_table(schema_name='dcp_sfpsd')
    # importer.import_table(schema_name='dep_wwtc')
    # importer.import_table(schema_name='dfta_contracts')
    # importer.import_table(schema_name='doe_busroutesgarages')
    # importer.import_table(schema_name='doe_lcgms')
    # importer.import_table(schema_name='doe_universalprek')
    # importer.import_table(schema_name='dohmh_daycare')
    # importer.import_table(schema_name='dot_bridgehouses')
    # importer.import_table(schema_name='dot_ferryterminals')
    # importer.import_table(schema_name='dot_mannedfacilities')
    # importer.import_table(schema_name='dot_pedplazas')
    # importer.import_table(schema_name='dot_publicparking')
    # importer.import_table(schema_name='dpr_parksproperties')
    # importer.import_table(schema_name='dsny_mtsgaragemaintenance')
    # importer.import_table(schema_name='dycd_afterschoolprograms')
    # importer.import_table(schema_name='fbop_corrections')
    # importer.import_table(schema_name='fdny_firehouses')
    # importer.import_table(schema_name='foodbankny_foodbanks')
    # importer.import_table(schema_name='hhc_hospitals')
    # importer.import_table(schema_name='hra_centers')
    # importer.import_table(schema_name='moeo_socialservicesiteloactions')
    # importer.import_table(schema_name='nycdoc_corrections')
    # importer.import_table(schema_name='nycha_communitycenters')
    # importer.import_table(schema_name='nycha_policeservice')
    # importer.import_table(schema_name='nycourts_courts')
    # importer.import_table(schema_name='nypl_libraries')
    # importer.import_table(schema_name='nysdec_lands')
    # importer.import_table(schema_name='nysdec_solidwaste')
    # importer.import_table(schema_name='nysdoccs_corrections')
    # importer.import_table(schema_name='nysdoh_healthfacilities')
    # importer.import_table(schema_name='nysdoh_nursinghomes')
    # importer.import_table(schema_name='nysed_activeinstitutions')
    # importer.import_table(schema_name='nysoasas_programs')
    # importer.import_table(schema_name='nysomh_mentalhealth')
    # importer.import_table(schema_name='nysopwdd_providers')
    # importer.import_table(schema_name='nysparks_historicplaces')
    # importer.import_table(schema_name='nysparks_parks')
    # importer.import_table(schema_name='qpl_libraries')
    # importer.import_table(schema_name='sbs_workforce1')
    # importer.import_table(schema_name='uscourts_courts')
    # importer.import_table(schema_name='usdot_airports')
    # importer.import_table(schema_name='usdot_ports')
    # importer.import_table(schema_name='usnps_parks')

if __name__ == "__main__":
    ETL()