DROP TABLE IF EXISTS facilities;
CREATE TABLE facilities (
uid text,
facname text,
factype text,
facsubgrp text,
facgroup text,
facdomain text,
servarea text,
opname text,
opabbrev text,
optype text,
overagency text,
overabbrev text,
overlevel text,
capacity text,
captype text,
proptype text,
datasource text,

-- spatial --> geosupport
addressnum text,
streetname text,
address text,
city text,
zipcode text,
boro text,
bin text,
bbl text,
latitude text,
longitude text,
xcoord text,
ycoord text,
commboard text,
nta text,
council text,
censtract text,
geom geometry(Geometry,4326)
);
