DELETE FROM facilities;

-- CALL load_to_facilities('acs_daycareheadstart');
CALL load_to_facilities('bpl_libraries');
CALL load_to_facilities('dca_operatingbusinesses');
-- CALL load_to_facilities('dcas_colp');
CALL load_to_facilities('dcla_culturalinstitutions');
CALL load_to_facilities('dcp_pops');
-- CALL load_to_facilities('dep_wwtc');
CALL load_to_facilities('dfta_contracts');
-- CALL load_to_facilities('doe_bluebook');
CALL load_to_facilities('doe_busroutesgarages');
CALL load_to_facilities('doe_lcgms');
-- CALL load_to_facilities('doe_universalprek');
CALL load_to_facilities('dohmh_daycare');
CALL load_to_facilities('dot_bridgehouses');
CALL load_to_facilities('dot_ferryterminals');
CALL load_to_facilities('dot_mannedfacilities');
-- CALL load_to_facilities('dot_pedplazas'); 
CALL load_to_facilities('dot_publicparking'); 
CALL load_to_facilities('dpr_parksproperties');
CALL load_to_facilities('dsny_mtsgaragemaintenance');
-- CALL load_to_facilities('dycd_afterschoolprograms');
-- CALL load_to_facilities('facilities_former'); place holder for records from SFPSD
-- CALL load_to_facilities('fbop_corrections');
CALL load_to_facilities('foodbankny_foodbanks');
-- CALL load_to_facilities('hhc_hospitals');
CALL load_to_facilities('hra_centers');
-- CALL load_to_facilities('moeo_socialservicesiteloactions');
-- CALL load_to_facilities('nycdoc_corrections');
-- CALL load_to_facilities('nycha_communitycenters');
CALL load_to_facilities('nycha_policeservice');
-- CALL load_to_facilities('nycourts_courts');
CALL load_to_facilities('nypl_libraries');
-- CALL load_to_facilities('nysdec_lands');
CALL load_to_facilities('nysdec_solidwaste');
-- CALL load_to_facilities('nysdoccs_corrections');
CALL load_to_facilities('nysdoh_healthfacilities');
CALL load_to_facilities('nysdoh_nursinghomes');
CALL load_to_facilities('nysed_activeinstitutions');
-- CALL load_to_facilities('nysoasas_programs');
-- CALL load_to_facilities('nysocfs_facilities');
CALL load_to_facilities('nysomh_mentalhealth');
CALL load_to_facilities('nysopwdd_providers');
-- CALL load_to_facilities('nysparks_historicplaces');
-- CALL load_to_facilities('nysparks_parks');
CALL load_to_facilities('qpl_libraries');
CALL load_to_facilities('sbs_workforce1');
-- CALL load_to_facilities('uscourts_courts');
CALL load_to_facilities('usdot_airports');
CALL load_to_facilities('usdot_ports');
CALL load_to_facilities('usnps_parks');